<?php

use App\Models\Permission;

class PermissionTableSeeder extends \Illuminate\Database\Seeder
{

    public function run()
    {
        $now = \Carbon\Carbon::now()->toDateTimeString();
        $info = Permission::create([
            'component' => 'Layout',
            'icon' => 'user',
            'name' => '个人信息',
            'router' => '/info',
            'sort' => 1,
        ]);

        $info_index = Permission::create([
                'component' => 'info/index',
                'icon' => 'user',
                'name' => '个人信息',
                'router' => '/index',
                'type' => Permission::MENU,
                'btn_key' => '',
                'pid' => $info->id,
                'sort' => 1,
                'method' => '',
        ]);

        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '更新',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'update',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,

            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改密码',
                'router' => 'yw_admin/me/update_password',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => 'PUT',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '获取登陆者该有的导航栏(必选)',
                'router' => "yw_admin/me/get_nav",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '个人信息(必选)',
                'router' => "yw_admin/me",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '退出登陆(必选)',
                'router' => "yw_admin/me/logout",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            //"yw_admin/roles_all"
            [
                'component' => '',
                'icon' => '',
                'name' => '获取所有角色(必选)',
                'router' => "yw_admin/roles_all",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '上传文件(必选)',
                'router' => "yw_admin/upload",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $info_index->id,
                'sort' => 1,
                'method' => 'POST',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
        ]);

        $system = Permission::create([
            'component' => 'Layout',
            'icon' => 'system',
            'name' => '系统管理',
            'router' => '/system',
            'sort' => 2,
        ]);
        $config = Permission::create([
            'component' => 'system/config',
            'name' => '系统配置',
            'router' => '/config',
            'pid' => $system->id,
            'sort' => 1,
        ]);

        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '添加配置',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'create',
                'pid' => $config->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改配置',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'update',
                'pid' => $config->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '更新配置',
                'router' => 'yw_admin/config/{id}',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $config->id,
                'sort' => 1,
                'method' => 'PUT',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '添加配置',
                'router' => 'yw_admin/config',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $config->id,
                'sort' => 1,
                'method' => 'POST',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '配置列表',
                'router' => 'yw_admin/config',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $config->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ]
        ]);


        $login_log = Permission::create([
            'component' => 'system/loginLog',
            'name' => '登陆日志',
            'router' => '/login_log',
            'pid' => $system->id,
            'sort' => 2,
        ]);

        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '日志列表',
                'router' => "yw_admin/login_log",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $login_log->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ]
        ]);

        $operating_log = Permission::create([
            'component' => 'system/operatingLog',
            'name' => '操作日志日志',
            'router' => '/operating_log',
            'pid' => $system->id,
            'sort' => 3,
        ]);

        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '操作日志列表',
                'router' => "yw_admin/operating_log",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $operating_log->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ]
        ]);

        $permission = Permission::create([
            'component' => 'Layout',
            'icon' => 'nested',
            'name' => '权限管理',
            'router' => '/permission',
            'sort' => 3,
        ]);

        $permissions = Permission::create([
            'component' => 'permission/permission',
            'name' => '权限',
            'router' => '/permissions',
            'pid' => $permission->id,
            'sort' => 1,
        ]);

        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '添加权限',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'create',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改权限',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'update',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '删除权限',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'delete',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '权限列表',
                'router' => 'yw_admin/permissions',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '添加权限',
                'router' => 'yw_admin/permissions',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'POST',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改权限',
                'router' => 'yw_admin/permissions/{permission}',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'PUT',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '删除权限',
                'router' => 'yw_admin/permissions/{permission}',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'DELETE',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '获取权限列表(交集)',
                'router' => "yw_admin/permissions/path/list",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '获取父级权限',
                'router' => "yw_admin/permissions/father",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '所有权限',
                'router' => "yw_admin/permissions/all",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '权限树',
                'router' => "yw_admin/permissions/tree",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $permissions->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ]
        ]);

        $administrators = Permission::create([
            'component' => 'permission/administrators',
            'name' => '管理员',
            'router' => '/administrators',
            'pid' => $permission->id,
            'sort' => 2,
        ]);
        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '添加管理员',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'create',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改管理员',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'update',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '删除管理员',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'delete',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '管理员列表',
                'router' => 'yw_admin/administrators',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '添加管理员',
                'router' => 'yw_admin/administrators',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => 'POST',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改管理员',
                'router' => 'yw_admin/administrators/{administrator}',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => 'PUT',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '删除管理员',
                'router' => 'yw_admin/administrators/{administrator}',
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $administrators->id,
                'sort' => 1,
                'method' => 'DELETE',
                'created_at'=>$now,
                'updated_at'=>$now,
            ]
        ]);

        $role= Permission::create([
            'component' => 'permission/role',
            'name' => '角色',
            'router' => '/role',
            'pid' => $permission->id,
            'sort' => 3,
        ]);
        Permission::insert([
            [
                'component' => '',
                'icon' => '',
                'name' => '添加角色',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'create',
                'pid' => $role->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改角色',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'update',
                'pid' => $role->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '删除角色',
                'router' => '',
                'type' => Permission::BUTTON,
                'btn_key' => 'delete',
                'pid' => $role->id,
                'sort' => 1,
                'method' => '',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '角色列表',
                'router' => "yw_admin/roles",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $role->id,
                'sort' => 1,
                'method' => 'GET',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '添加角色',
                'router' => "yw_admin/roles",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $role->id,
                'sort' => 1,
                'method' => 'POST',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '修改角色',
                'router' => "yw_admin/roles/{role}",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $role->id,
                'sort' => 1,
                'method' => 'PUT',
                'created_at'=>$now,
                'updated_at'=>$now,
            ],
            [
                'component' => '',
                'icon' => '',
                'name' => '删除角色',
                'router' => "yw_admin/roles/{role}",
                'type' => Permission::INTERFACES,
                'btn_key' => '',
                'pid' => $role->id,
                'sort' => 1,
                'method' => 'DELETE',
                'created_at'=>$now,
                'updated_at'=>$now,
            ]
        ]);




    }

}
